

export type getAccessibilityData = () => UTSJSONObject;

export interface Uni {
	/**
	 * 获取无障碍服务信息1
	 * @tutorial https://doc.dcloud.net.cn/uni-app-x/api/get-accessibility-info.html#getAccessibilityData
	 * @tutorial_uni_app_x https://doc.dcloud.net.cn/uni-app-x/api/get-accessibility-info.html#getAccessibilityData
	 * @uniPlatform
	 * {
	 * 	"app": {
	 * 		"android": {
	 * 			"osVer": "5.0",
	 * 			"uniVer": "x",
	 * 			"unixVer": "4.51"
	 * 		},
	 * 		"ios": {
	 * 			"osVer": "x",
	 * 			"uniVer": "x",
	 * 			"unixVer": "x"
	 * 		},
	 *    "harmony": {
	 *      "osVer": "x",
	 *      "uniVer": "x",
	 *      "unixVer": "x"
	 *    }
	 * 	}
	 * }
	 * @example
	 ```typescript
	  uni.getAccessibilityData()
	 ```
	 * @return {object}
	 */
	getAccessibilityData() : UTSJSONObject;
}
