// #ifdef WEB
class UniCustomEvent<T> {
  detail : T
  constructor(type : string, detail : T) {
    // this.type = type
    this.detail = detail
  }
}
// #endif

export type UniEditorFocusEventDetail = {
  html : string,
  text : string,
  delta : any
}
export class UniEditorFocusEvent extends UniCustomEvent<UniEditorFocusEventDetail> {
  constructor(html : string, text : string, delta : any) {
    super('focus', { html, text, delta } as UniEditorFocusEventDetail)
  }
}

export type UniEditorBlurEventDetail = {
  html : string,
  text : string,
  delta : any
}
export class UniEditorBlurEvent extends UniCustomEvent<UniEditorBlurEventDetail> {
  constructor(html : string, text : string, delta : any) {
    super('blur', { html, text, delta } as UniEditorBlurEventDetail)
  }
}

export type UniEditorInputEventDetail = {
  html : string,
  text : string,
  delta : any
}
export class UniEditorInputEvent extends UniCustomEvent<UniEditorInputEventDetail> {
  constructor(html : string, text : string, delta : any) {
    super('input', { html, text, delta } as UniEditorInputEventDetail)
  }
}

export type UniEditorStatusChangeEventDetail = {
  bold?: boolean
  italic?: boolean
  underline?: boolean
  strike?: boolean
  align?: string
  lineHeight?: boolean
  letterSpacing?: boolean
  marginTop?: boolean
  marginBottom?: boolean
  fontFamily?: boolean
  fontSize?: string
  color?: string
  backgroundColor?: string
  list?: string
  header?: number
  script?: string
  direction?: string
}
export class UniEditorStatusChangeEvent extends UniCustomEvent<UniEditorStatusChangeEventDetail> {
  constructor(formats: UniEditorStatusChangeEventDetail) {
    super('statuschange', formats as UniEditorStatusChangeEventDetail)
  }
}

// #ifdef WEB
// vapor 临时处理
class UniVueElement extends HTMLElement { }
// #endif

// #ifdef !WEB && (MP || !VUE3-VAPOR)
// vapor 临时处理
class UniVueElement extends UniElement { }
// #endif

type OptionsSuccessRes = {
  errMsg: string
}
type OptionsFailRes = {
  errMsg: string
}
type OptionsCompleteRes = {
  errMsg: string
}

type Options = {
  success: (res: OptionsSuccessRes) => void
  fail: (res: OptionsFailRes) => void
  complete: (res: OptionsCompleteRes) => void
}

type InsertImageOptions = {
  src?: string | null,
  alt?: string | null,
  width?: string | null,
  height?: string | null,
  extClass?: string | null,
  data?: any,
  success: (res: OptionsSuccessRes) => void
  fail: (res: OptionsFailRes) => void
  complete: (res: OptionsCompleteRes) => void
}

type InsertTextOptions = {
  text?: string | null,
  success: (res: OptionsSuccessRes) => void
  fail: (res: OptionsFailRes) => void
  complete: (res: OptionsCompleteRes) => void
}

type SetContentsOptions = {
  delta?: any,
  html?: string | null,
  success: (res: OptionsSuccessRes) => void
  fail: (res: OptionsFailRes) => void
  complete: (res: OptionsCompleteRes) => void
}

type GetSelectionTextOptionsRes = {
  text: string
}

type GetSelectionTextOptions = {
  success: (res: GetSelectionTextOptionsRes) => void
  fail: (res: OptionsFailRes) => void
  complete: (res: OptionsCompleteRes) => void
}

export class UniEditorElement extends UniVueElement {
  override tagName : string = 'EDITOR'
  override nodeName : string = 'EDITOR'

  /**
   * 格式化文本
   * @param name format name
   * @param value format value, optional, default is null
   */
  format(name: string, value: string | number | null = null) : void {
    this.vm?.format(name, value)
  }

  /**
   * 插入分割线
   * @param options 回调选项 { success, fail, complete }
   */
  insertDivider(options : Options | null) : void {
    this.vm?.insertDivider(options)
  }

  /**
   * 插入图片
   * @param options 图片选项 { src, alt, width, height, extClass, data, success, fail, complete }
   */
  insertImage(options : InsertImageOptions | null) : void {
    this.vm?.insertImage(options)
  }

  /**
   * 插入文本
   * @param options 文本选项 { text, success, fail, complete }
   */
  insertText(options : InsertTextOptions | null) : void {
    this.vm?.insertText(options)
  }

  /**
   * 设置内容
   * @param options 内容选项 { delta, html, success, fail, complete }
   */
  setContents(options : SetContentsOptions | null) : void {
    this.vm?.setContents(options)
  }

  /**
   * 获取内容
   * @param options 回调选项 { success, fail, complete }
   * @returns 在 success 回调中返回 { html, text, delta }
   */
  getContents(options : Options | null) : void {
    this.vm?.getContents(options)
  }

  /**
   * 清空内容
   * @param options 回调选项 { success, fail, complete }
   */
  clear(options : Options | null) : void {
    this.vm?.clear(options)
  }

  /**
   * 移除格式
   * @param options 回调选项 { success, fail, complete }
   */
  removeFormat(options : Options | null) : void {
    this.vm?.removeFormat(options)
  }

  /**
   * 撤销
   * @param options 回调选项 { success, fail, complete }
   */
  undo(options : Options | null) : void {
    this.vm?.undo(options)
  }

  /**
   * 重做
   * @param options 回调选项 { success, fail, complete }
   */
  redo(options : Options | null) : void {
    this.vm?.redo(options)
  }

  /**
   * 失去焦点
   * @param options 回调选项 { success, fail, complete }
   */
  override blur(options : Options | null) : void {
    this.vm?.blur(options)
  }

  /**
   * 获取选中文本
   * @param options 回调选项 { success, fail, complete }
   * @returns 在 success 回调中返回 { text }
   */
  getSelectionText(options : GetSelectionTextOptions | null) : void {
    this.vm?.getSelectionText(options)
  }

  /**
   * 滚动到可视区域
   * @param options 回调选项 { success, fail, complete }
   */
  scrollIntoView(options : Options | null) : void {
    this.vm?.scrollIntoView(options)
  }
}
