export const formatTime = (time : number) : string => {
  if (typeof time !== 'number' || time < 0) {
    return time.toString()
  }

  var hour = parseInt((time / 3600).toString())
  time = time % 3600
  var minute = parseInt((time / 60).toString())
  time = time % 60
  var second = time
  return [hour, minute, second].map((n : number) => {
    let str = n.toString();
    return str.length > 1 ? str : "0" + str;
  }).join(":");
}
